//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFC.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCompound
    {
        public long OrderID { get; set; }
        public long DishID { get; set; }
        public string Status { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual DishStatus DishStatus { get; set; }
        public virtual Order Order { get; set; }
    }
}
